const JSON_HEADERS={"content-type":"application/json;charset=UTF-8"};
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS"};
const out=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...cors}});
const id=()=>crypto.randomUUID();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function sha256(s){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))}
async function hashPassword(password,salt=id()){const data=new TextEncoder().encode(password);const key=await crypto.subtle.importKey("raw",data,"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:100000,hash:"SHA-256"},key,256);return "pbkdf2$100000$"+salt+"$"+hex(bits)}
async function verifyPassword(password,stored){const [kind,it,salt,want]=stored.split("$");if(kind!=="pbkdf2")return false;const data=new TextEncoder().encode(password);const key=await crypto.subtle.importKey("raw",data,"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:Number(it),hash:"SHA-256"},key,256);return hex(bits)===want}
async function userFromRequest(req,env){const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))return null;const token=h.slice(7);const th=await sha256(token);return env.DB.prepare(`SELECT u.id,u.full_name,u.username,u.role,u.is_active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.is_active=1`).bind(th).first()}
async function canClass(env,u,classId){if(u.role==="SECTION_HEAD")return true;return !!await env.DB.prepare("SELECT 1 ok FROM teacher_class_assignments WHERE teacher_id=? AND class_id=? AND is_active=1").bind(u.id,classId).first()}
async function json(req){try{return await req.json()}catch{return null}}

export default {async fetch(req,env){
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
  const url=new URL(req.url), p=url.pathname.replace(/\/$/,"")||"/";
  try{
    if(p==="/api/health") return out({ok:true,service:"school-attendance-api",database:"D1"});
    if(p==="/api/setup/status"&&req.method==="GET"){
      const row=await env.DB.prepare("SELECT COUNT(*) count FROM users WHERE role='SECTION_HEAD'").first();
      return out({needs_section_head:Number(row?.count||0)===0});
    }
    if(p==="/api/setup/section-head"&&req.method==="POST"){
      const exists=await env.DB.prepare("SELECT 1 FROM users WHERE role='SECTION_HEAD' LIMIT 1").first();
      if(exists)return out({error:"initial_setup_complete"},409);
      const b=await json(req); if(!b?.full_name||!b?.username||!b?.password||b.password.length<10)return out({error:"full_name_username_and_password_min_10_required"},400);
      const uid=id(), ph=await hashPassword(b.password);
      await env.DB.prepare("INSERT INTO users(id,full_name,email,username,password_hash,role) VALUES(?,?,?,?,?, 'SECTION_HEAD')").bind(uid,b.full_name.trim(),b.username.trim().toLowerCase()+'@local.invalid',b.username.trim().toLowerCase(),ph).run();
      return out({ok:true,user_id:uid},201);
    }
    if(p==="/api/auth/login"&&req.method==="POST"){
      const b=await json(req); const u=await env.DB.prepare("SELECT * FROM users WHERE username=? COLLATE NOCASE AND is_active=1").bind(b?.username||"").first();
      if(!u||!await verifyPassword(b?.password||"",u.password_hash))return out({error:"invalid_credentials"},401);
      const token=hex(crypto.getRandomValues(new Uint8Array(32))), th=await sha256(token), sid=id();
      await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(sid,u.id,th).run();
      return out({token,user:{id:u.id,full_name:u.full_name,username:u.username,role:u.role}});
    }
    const u=await userFromRequest(req,env); if(!u)return out({error:"unauthorized"},401);
    if(p==="/api/auth/me"&&req.method==="GET")return out({user:u});
    if(p==="/api/profile"&&req.method==="PUT"){const b=await json(req);const name=String(b?.full_name||"").trim();if(name.length<2||name.length>100)return out({error:"name_must_be_2_to_100_characters"},400);await env.DB.prepare("UPDATE users SET full_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,u.id).run();await env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,new_values) VALUES(?,?,?,?,?)").bind(u.id,"PROFILE_UPDATED","user",u.id,JSON.stringify({full_name:name})).run();return out({user:{...u,full_name:name}})}
    if(p==="/api/auth/logout"&&req.method==="POST"){const h=req.headers.get("authorization").slice(7);await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(h)).run();return out({ok:true})}
    if(p==="/api/classes"&&req.method==="GET"){
      const q=u.role==="SECTION_HEAD"?"SELECT * FROM classes WHERE is_active=1 ORDER BY display_name":"SELECT c.* FROM classes c JOIN teacher_class_assignments a ON a.class_id=c.id WHERE a.teacher_id=? AND a.is_active=1 AND c.is_active=1 ORDER BY c.display_name";
      const r=u.role==="SECTION_HEAD"?await env.DB.prepare(q).all():await env.DB.prepare(q).bind(u.id).all();return out({classes:r.results});
    }
    const sm=p.match(/^\/api\/classes\/([^/]+)\/students$/);
    if(sm&&req.method==="GET"){const classId=decodeURIComponent(sm[1]);if(!await canClass(env,u,classId))return out({error:"forbidden"},403);const r=await env.DB.prepare("SELECT id,admission_number,full_name,class_id FROM students WHERE class_id=? AND is_active=1 ORDER BY full_name").bind(classId).all();return out({students:r.results})}
    if(p==="/api/attendance"&&req.method==="POST"){
      const b=await json(req);if(!b?.class_id||!/^\d{4}-\d{2}-\d{2}$/.test(b?.date||"")||!Array.isArray(b?.records))return out({error:"invalid_request"},400);
      if(!await canClass(env,u,b.class_id))return out({error:"forbidden"},403);
      const blocked=await env.DB.prepare("SELECT 1 FROM school_days WHERE day=? AND day_type IN ('WEEKEND','HOLIDAY','SPECIAL_HOLIDAY')").bind(b.date).first();if(blocked)return out({error:"not_a_school_day"},409);
      const students=(await env.DB.prepare("SELECT id FROM students WHERE class_id=? AND is_active=1").bind(b.class_id).all()).results;const allowed=new Set(students.map(x=>x.id));
      if(!students.length||b.records.length!==students.length||new Set(b.records.map(x=>x.student_id)).size!==students.length||b.records.some(x=>!allowed.has(x.student_id)||!["PRESENT","ABSENT"].includes(x.status)))return out({error:"incomplete_or_invalid_register"},400);
      const sid=id();const stmts=[env.DB.prepare("INSERT INTO attendance_sessions(id,class_id,attendance_date,submitted_by) VALUES(?,?,?,?)").bind(sid,b.class_id,b.date,u.id)];
      for(const r of b.records)stmts.push(env.DB.prepare("INSERT INTO attendance_records(id,session_id,student_id,status,marked_by) VALUES(?,?,?,?,?)").bind(id(),sid,r.student_id,r.status,u.id));
      stmts.push(env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,new_values) VALUES(?,?,?,?,?)").bind(u.id,"ATTENDANCE_SUBMITTED","attendance_session",sid,JSON.stringify({class_id:b.class_id,date:b.date,count:b.records.length})));
      try{await env.DB.batch(stmts)}catch(e){if(String(e).includes("UNIQUE"))return out({error:"attendance_already_submitted"},409);throw e}return out({ok:true,session_id:sid},201);
    }
    if(p==="/api/dashboard/today"&&req.method==="GET"){
      if(u.role!=="SECTION_HEAD")return out({error:"forbidden"},403);const date=url.searchParams.get("date")||new Date().toISOString().slice(0,10);
      const r=await env.DB.prepare(`SELECT c.id class_id,c.display_name,s.id session_id,s.submitted_at,COUNT(ar.id) total,SUM(CASE WHEN ar.status='PRESENT' THEN 1 ELSE 0 END) present,SUM(CASE WHEN ar.status='ABSENT' THEN 1 ELSE 0 END) absent,SUM(CASE WHEN ar.status='LATE' THEN 1 ELSE 0 END) late FROM classes c LEFT JOIN attendance_sessions s ON s.class_id=c.id AND s.attendance_date=? LEFT JOIN attendance_records ar ON ar.session_id=s.id WHERE c.is_active=1 GROUP BY c.id,c.display_name,s.id,s.submitted_at ORDER BY c.display_name`).bind(date).all();return out({date,classes:r.results});
    }

    if(u.role==="SECTION_HEAD"&&p==="/api/students"&&req.method==="GET"){const r=await env.DB.prepare("SELECT s.*,c.display_name FROM students s JOIN classes c ON c.id=s.class_id ORDER BY s.full_name").all();return out({students:r.results})}
    if(u.role==="SECTION_HEAD"&&p==="/api/students"&&req.method==="POST"){const b=await json(req);if(!b?.admission_number||!b?.full_name||!b?.class_id)return out({error:"invalid_request"},400);const sid=id();try{await env.DB.prepare("INSERT INTO students(id,admission_number,full_name,class_id) VALUES(?,?,?,?)").bind(sid,b.admission_number.trim(),b.full_name.trim(),b.class_id).run()}catch(e){if(String(e).includes("UNIQUE"))return out({error:"admission_number_exists"},409);throw e}await env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,new_values) VALUES(?,?,?,?,?)").bind(u.id,"STUDENT_CREATED","student",sid,JSON.stringify(b)).run();return out({ok:true,id:sid},201)}
    const stu=p.match(/^\/api\/students\/([^/]+)$/);if(u.role==="SECTION_HEAD"&&stu&&req.method==="PUT"){const b=await json(req),sid=decodeURIComponent(stu[1]);const old=await env.DB.prepare("SELECT * FROM students WHERE id=?").bind(sid).first();if(!old)return out({error:"not_found"},404);if(b.class_id&&b.class_id!==old.class_id)await env.DB.prepare("INSERT INTO student_class_history(id,student_id,from_class_id,to_class_id,transferred_by,reason) VALUES(?,?,?,?,?,?)").bind(id(),sid,old.class_id,b.class_id,u.id,b.reason||null).run();await env.DB.prepare("UPDATE students SET admission_number=COALESCE(?,admission_number),full_name=COALESCE(?,full_name),class_id=COALESCE(?,class_id),is_active=COALESCE(?,is_active),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.admission_number??null,b.full_name??null,b.class_id??null,b.is_active===undefined?null:(b.is_active?1:0),sid).run();await env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,old_values,new_values) VALUES(?,?,?,?,?,?)").bind(u.id,"STUDENT_UPDATED","student",sid,JSON.stringify(old),JSON.stringify(b)).run();return out({ok:true})}
    if(u.role==="SECTION_HEAD"&&p==="/api/teachers"&&req.method==="GET"){const r=await env.DB.prepare("SELECT id,full_name,username,is_active,created_at FROM users WHERE role='TEACHER' ORDER BY full_name").all();for(const t of r.results){t.classes=(await env.DB.prepare("SELECT c.id,c.display_name FROM teacher_class_assignments a JOIN classes c ON c.id=a.class_id WHERE a.teacher_id=? AND a.is_active=1 ORDER BY c.display_name").bind(t.id).all()).results}return out({teachers:r.results})}
    if(u.role==="SECTION_HEAD"&&p==="/api/teachers"&&req.method==="POST"){const b=await json(req);if(!b?.full_name||!b?.username||!b?.password||b.password.length<10)return out({error:"invalid_request"},400);const tid=id(),ph=await hashPassword(b.password);try{await env.DB.prepare("INSERT INTO users(id,full_name,email,username,password_hash,role) VALUES(?,?,?,?,?,'TEACHER')").bind(tid,b.full_name.trim(),b.username.trim().toLowerCase()+"@local.invalid",b.username.trim().toLowerCase(),ph).run()}catch(e){if(String(e).includes("UNIQUE"))return out({error:"username_exists"},409);throw e}for(const cid of (b.class_ids||[]))await env.DB.prepare("INSERT OR REPLACE INTO teacher_class_assignments(teacher_id,class_id,assigned_by,is_active) VALUES(?,?,?,1)").bind(tid,cid,u.id).run();await env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,new_values) VALUES(?,?,?,?,?)").bind(u.id,"TEACHER_CREATED","user",tid,JSON.stringify({full_name:b.full_name,username:b.username,class_ids:b.class_ids||[]})).run();return out({ok:true,id:tid},201)}
    const tea=p.match(/^\/api\/teachers\/([^/]+)$/);if(u.role==="SECTION_HEAD"&&tea&&req.method==="PUT"){const tid=decodeURIComponent(tea[1]),b=await json(req);if(b.password&&b.password.length<10)return out({error:"password_min_10"},400);const ph=b.password?await hashPassword(b.password):null;await env.DB.prepare("UPDATE users SET full_name=COALESCE(?,full_name),is_active=COALESCE(?,is_active),password_hash=COALESCE(?,password_hash),updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='TEACHER'").bind(b.full_name??null,b.is_active===undefined?null:(b.is_active?1:0),ph,tid).run();if(Array.isArray(b.class_ids)){await env.DB.prepare("UPDATE teacher_class_assignments SET is_active=0 WHERE teacher_id=?").bind(tid).run();for(const cid of b.class_ids)await env.DB.prepare("INSERT INTO teacher_class_assignments(teacher_id,class_id,assigned_by,is_active) VALUES(?,?,?,1) ON CONFLICT(teacher_id,class_id) DO UPDATE SET is_active=1,assigned_by=excluded.assigned_by").bind(tid,cid,u.id).run()}await env.DB.prepare("DELETE FROM sessions WHERE user_id=? AND ?=0").bind(tid,b.is_active===false?0:1).run();return out({ok:true})}
    if(p==="/api/history"&&req.method==="GET"){const cid=url.searchParams.get("class_id"),from=url.searchParams.get("from")||"0000-01-01",to=url.searchParams.get("to")||"9999-12-31";let q="SELECT s.id session_id,s.class_id,c.display_name,s.attendance_date,s.submitted_at,u.full_name submitted_by,COUNT(r.id) total,SUM(r.status='PRESENT') present,SUM(r.status='ABSENT') absent,SUM(r.status='LATE') late FROM attendance_sessions s JOIN classes c ON c.id=s.class_id JOIN users u ON u.id=s.submitted_by LEFT JOIN attendance_records r ON r.session_id=s.id WHERE s.attendance_date BETWEEN ? AND ?";const binds=[from,to];if(cid){if(!await canClass(env,u,cid))return out({error:"forbidden"},403);q+=" AND s.class_id=?";binds.push(cid)}else if(u.role!=="SECTION_HEAD")return out({error:"class_id_required"},400);q+=" GROUP BY s.id ORDER BY s.attendance_date DESC,s.submitted_at DESC LIMIT 500";const rr=await env.DB.prepare(q).bind(...binds).all();return out({sessions:rr.results})}
    const ses=p.match(/^\/api\/attendance\/([^/]+)$/);if(ses&&req.method==="GET"){const sid=decodeURIComponent(ses[1]);const s=await env.DB.prepare("SELECT s.*,c.display_name FROM attendance_sessions s JOIN classes c ON c.id=s.class_id WHERE s.id=?").bind(sid).first();if(!s)return out({error:"not_found"},404);if(!await canClass(env,u,s.class_id))return out({error:"forbidden"},403);const rr=await env.DB.prepare("SELECT r.id record_id,r.student_id,st.admission_number,st.full_name,r.status FROM attendance_records r JOIN students st ON st.id=r.student_id WHERE r.session_id=? ORDER BY st.full_name").bind(sid).all();return out({session:s,records:rr.results})}
    const rec=p.match(/^\/api\/attendance\/records\/([^/]+)$/);if(rec&&req.method==="PUT"){const rid=decodeURIComponent(rec[1]),b=await json(req);if(!["PRESENT","ABSENT"].includes(b?.status)||!b?.reason)return out({error:"status_and_reason_required"},400);const old=await env.DB.prepare("SELECT r.*,s.class_id FROM attendance_records r JOIN attendance_sessions s ON s.id=r.session_id WHERE r.id=?").bind(rid).first();if(!old)return out({error:"not_found"},404);if(u.role!=="SECTION_HEAD"&&!await canClass(env,u,old.class_id))return out({error:"forbidden"},403);if(old.status!==b.status){await env.DB.batch([env.DB.prepare("UPDATE attendance_records SET status=?,marked_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.status,u.id,rid),env.DB.prepare("INSERT INTO attendance_changes(id,attendance_record_id,old_status,new_status,changed_by,reason) VALUES(?,?,?,?,?,?)").bind(id(),rid,old.status,b.status,u.id,b.reason),env.DB.prepare("INSERT INTO audit_logs(user_id,action,target_type,target_id,old_values,new_values) VALUES(?,?,?,?,?,?)").bind(u.id,"ATTENDANCE_CORRECTED","attendance_record",rid,JSON.stringify({status:old.status}),JSON.stringify({status:b.status,reason:b.reason}))])}return out({ok:true})}
    if(u.role==="SECTION_HEAD"&&p==="/api/reports"&&req.method==="GET"){const from=url.searchParams.get("from")||"0000-01-01",to=url.searchParams.get("to")||"9999-12-31",cid=url.searchParams.get("class_id");let q="SELECT st.id student_id,st.admission_number,st.full_name,c.display_name,COUNT(r.id) total,SUM(r.status='PRESENT') present,SUM(r.status='ABSENT') absent,SUM(r.status='LATE') late,ROUND(100.0*SUM(r.status IN ('PRESENT','LATE'))/NULLIF(COUNT(r.id),0),1) attendance_percentage FROM attendance_records r JOIN attendance_sessions s ON s.id=r.session_id JOIN students st ON st.id=r.student_id JOIN classes c ON c.id=s.class_id WHERE s.attendance_date BETWEEN ? AND ?";const bs=[from,to];if(cid){q+=" AND s.class_id=?";bs.push(cid)}q+=" GROUP BY st.id,c.display_name ORDER BY c.display_name,st.full_name";const rr=await env.DB.prepare(q).bind(...bs).all();return out({report:rr.results})}
    if(u.role==="SECTION_HEAD"&&p==="/api/calendar"&&req.method==="GET"){const rr=await env.DB.prepare("SELECT * FROM school_days ORDER BY day DESC LIMIT 500").all();return out({days:rr.results})}
    if(u.role==="SECTION_HEAD"&&p==="/api/calendar"&&req.method==="POST"){const b=await json(req);if(!/^\d{4}-\d{2}-\d{2}$/.test(b?.day||"")||!["SCHOOL_DAY","WEEKEND","HOLIDAY","SPECIAL_HOLIDAY","SPECIAL_SCHOOL_DAY"].includes(b?.day_type))return out({error:"invalid_request"},400);await env.DB.prepare("INSERT INTO school_days(day,day_type,label,created_by) VALUES(?,?,?,?) ON CONFLICT(day) DO UPDATE SET day_type=excluded.day_type,label=excluded.label,created_by=excluded.created_by").bind(b.day,b.day_type,b.label||null,u.id).run();return out({ok:true})}
    if(u.role==="SECTION_HEAD"&&p==="/api/calendar"&&req.method==="DELETE"){const day=url.searchParams.get("day");await env.DB.prepare("DELETE FROM school_days WHERE day=?").bind(day).run();return out({ok:true})}
    if(u.role==="SECTION_HEAD"&&p==="/api/audit"&&req.method==="GET"){const rr=await env.DB.prepare("SELECT a.*,u.full_name,u.username FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500").all();return out({logs:rr.results})}
    if(u.role==="SECTION_HEAD"&&p==="/api/settings"&&req.method==="GET"){const rr=await env.DB.prepare("SELECT key,value,updated_at FROM system_settings ORDER BY key").all();return out({settings:Object.fromEntries(rr.results.map(x=>[x.key,x.value]))})}
    if(u.role==="SECTION_HEAD"&&p==="/api/settings"&&req.method==="PUT"){const b=await json(req);for(const [k,v] of Object.entries(b||{})){if(!["attendance_threshold","school_timezone","teacher_correction_allowed"].includes(k))continue;await env.DB.prepare("INSERT INTO system_settings(key,value,updated_by,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").bind(k,String(v),u.id).run()}return out({ok:true})}

    return out({error:"not_found"},404);
  }catch(e){console.error(e);return out({error:"internal_server_error"},500)}
}};