import { useEffect,useMemo,useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CheckCircle2,CloudOff,Search } from 'lucide-react'
import { clearDraft,loadDraft,saveDraft } from '../lib/drafts'
import { schoolDate,prettyDate } from '../lib/date'
import { supabase } from '../lib/supabase'
import { totals } from '../lib/attendance'
import type { AttendanceStatus,SchoolClass,Student } from '../types'

export function Attendance(){const [params]=useSearchParams(),today=schoolDate();const [classes,setClasses]=useState<SchoolClass[]>([]),[classId,setClassId]=useState(params.get('class')||''),[students,setStudents]=useState<Student[]>([]),[statuses,setStatuses]=useState<Record<string,AttendanceStatus>>({}),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[already,setAlready]=useState(false)
 useEffect(()=>{supabase.from('classes').select('id,display_name,grade_id').eq('is_active',true).order('display_name').then(({data})=>{setClasses((data||[]) as SchoolClass[]);if(!classId&&data?.length)setClassId(data[0].id)})},[])
 useEffect(()=>{if(!classId)return;(async()=>{setMessage('');const [{data:s},{data:session}]=await Promise.all([supabase.from('students').select('*').eq('class_id',classId).eq('is_active',true).order('admission_number'),supabase.from('attendance_sessions').select('id').eq('class_id',classId).eq('attendance_date',today).maybeSingle()]);setStudents((s||[]) as Student[]);setAlready(!!session);const draft=loadDraft(classId,today);setStatuses(draft?.statuses||Object.fromEntries((s||[]).map(x=>[x.id,'PRESENT'])))})()},[classId,today])
 useEffect(()=>{if(classId&&Object.keys(statuses).length)saveDraft({classId,date:today,statuses,updatedAt:new Date().toISOString()})},[classId,statuses,today])
 const count=useMemo(()=>totals(statuses),[statuses]),filtered=students.filter(s=>`${s.admission_number} ${s.full_name}`.toLowerCase().includes(query.toLowerCase())),selected=classes.find(c=>c.id===classId)
 function mark(id:string,status:AttendanceStatus){setStatuses(x=>({...x,[id]:status}))}
 async function submit(){if(!navigator.onLine){setMessage('Attendance could not be submitted. Your changes are still saved on this device.');return}if(Object.keys(statuses).length!==students.length){setMessage('Every active student needs a status.');return}if(!confirm(`Submit attendance for Class ${selected?.display_name} for ${prettyDate(today)}?\n\nPresent: ${count.present}  Absent: ${count.absent}  Late: ${count.late}`))return;setBusy(true);setMessage('');const records=students.map(s=>({student_id:s.id,status:statuses[s.id]}));const {error}=await supabase.rpc('submit_attendance',{p_class_id:classId,p_date:today,p_records:records});if(error){setMessage(error.message.includes('already')?'Attendance has already been submitted.':`Attendance could not be submitted. Your changes are still saved on this device. (${error.message})`)}else{clearDraft(classId,today);setAlready(true);setMessage('Attendance Submitted ✓')}setBusy(false)}
 return <><div className="page-title"><div><h1>Attendance Register</h1><p>{prettyDate(today)}</p></div><select value={classId} onChange={e=>setClassId(e.target.value)} aria-label="Class">{classes.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select></div>{!navigator.onLine&&<div className="offline"><CloudOff/> Offline — this unfinished register is saved on this device.</div>}{already?<section className="success-panel"><CheckCircle2/><h2>Attendance Submitted</h2><p>This class already has a confirmed register for today. Open History to review it.</p></section>:<><div className="attendance-tools"><button className="primary" onClick={()=>setStatuses(Object.fromEntries(students.map(s=>[s.id,'PRESENT'])))}>Mark All Present</button><label className="search"><Search/><input placeholder="Name or admission number" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="totals"><span className="present">Present <b>{count.present}</b></span><span className="absent">Absent <b>{count.absent}</b></span><span className="late">Late <b>{count.late}</b></span><span>Total <b>{students.length}</b></span></div><section className="student-list">{filtered.map(s=><article key={s.id}><div><small>{s.admission_number}</small><strong>{s.full_name}</strong></div><div className="status-control" role="group" aria-label={`Attendance for ${s.full_name}`}>{(['PRESENT','ABSENT','LATE'] as const).map(status=><button key={status} className={statuses[s.id]===status?status.toLowerCase():''} onClick={()=>mark(s.id,status)} aria-pressed={statuses[s.id]===status}>{status==='PRESENT'?'P':status==='ABSENT'?'A':'L'}<span>{status[0]+status.slice(1).toLowerCase()}</span></button>)}</div></article>)}</section>{message&&<div className={message.includes('✓')?'notice':'error'}>{message}</div>}<button className="submit" disabled={busy||!students.length} onClick={submit}>{busy?'Submitting to server…':'Submit Attendance'}</button></>}</>}

