import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {AlertCircle,CheckCircle2,Clock3,Users} from 'lucide-react'
import {useAuth} from '../AuthContext'
import {api} from '../lib/api'
import {schoolDate,prettyDate} from '../lib/date'
import type {SchoolClass} from '../types'
type Summary=SchoolClass&{session_id:string|null;submitted_at:string|null;total:number;present:number;absent:number;late:number}
export function Dashboard(){const {profile}=useAuth();return profile?.role==='SECTION_HEAD'?<AdminDashboard/>:<TeacherDashboard/>}
function TeacherDashboard(){const {profile}=useAuth();const [classes,setClasses]=useState<SchoolClass[]>([]);const today=schoolDate();useEffect(()=>{api<{classes:SchoolClass[]}>('/api/classes').then(x=>setClasses(x.classes)).catch(()=>setClasses([]))},[])
 return <><div className="page-title"><div><h1>Good day, {profile?.full_name.split(' ')[0]}</h1><p>{prettyDate(today)}</p></div></div><div className="teacher-hero"><Clock3/><div><small>TODAY'S ATTENDANCE</small><h2>{classes.length?`${classes.length} assigned class${classes.length===1?'':'es'}`:'No class assigned'}</h2></div></div><div className="class-grid">{classes.map(c=><article className="class-card" key={c.id}><div><span className="class-badge">{c.display_name}</span><h3>Ready to mark attendance</h3><p>Open the register and submit today's attendance.</p></div><Link className="primary" to={`/attendance?class=${c.id}`}>Open Attendance</Link></article>)}</div></>}
function AdminDashboard(){const today=schoolDate();const [rows,setRows]=useState<Summary[]>([]),[error,setError]=useState('');async function load(){try{const x=await api<{classes:Summary[]}>(`/api/dashboard/today?date=${today}`);setRows(x.classes);setError('')}catch{setError('Could not load the dashboard.')}}useEffect(()=>{load()},[today]);const submitted=rows.filter(x=>x.session_id),pending=rows.filter(x=>!x.session_id);const totals=rows.reduce((a,s)=>({present:a.present+Number(s.present||0),absent:a.absent+Number(s.absent||0),late:a.late+Number(s.late||0),total:a.total+Number(s.total||0)}),{present:0,absent:0,late:0,total:0});const pct=totals.total?((totals.present+totals.late)*100/totals.total).toFixed(1):'—'
 return <><div className="page-title"><div><h1>Today's Attendance</h1><p>{prettyDate(today)} · Cloudflare live data</p></div><button className="secondary" onClick={load}>Refresh</button></div>{error&&<div className="error">{error}</div>}<div className="stats"><Stat label="Present" value={totals.present} tone="green"/><Stat label="Absent" value={totals.absent} tone="red"/><Stat label="Late" value={totals.late} tone="amber"/><Stat label="Attendance" value={`${pct}%`} tone="blue"/><Stat label="Submitted" value={`${submitted.length}/${rows.length}`} tone="blue"/></div>{pending.length>0&&<section className="pending"><AlertCircle/><div><strong>Pending Classes</strong><p>{pending.map(c=>c.display_name).join(' · ')}</p></div></section>}<div className="grade-columns">{['10','11'].map(grade=><section className="panel" key={grade}><h2>Grade {grade}</h2>{rows.filter(c=>c.display_name.startsWith(grade+'-')).map(c=><div className="submission-row" key={c.id}><span className="class-badge">{c.display_name}</span>{c.session_id?<><span className="submitted"><CheckCircle2/> Submitted</span><span>{c.present}/{c.total}</span><strong>{c.total?(((c.present+c.late)*100/c.total).toFixed(1)):'—'}%</strong></>:<><span className="waiting"><Clock3/> Not submitted</span><span>—</span><strong>—</strong></>}</div>)}</section>)}</div></>}
function Stat({label,value,tone}:{label:string,value:string|number,tone:string}){return <article className={`stat ${tone}`}><small>{label}</small><strong>{value}</strong><Users size={19}/></article>}
