import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertCircle,CheckCircle2,Clock3,Users } from 'lucide-react'
import { useAuth } from '../AuthContext'
import { schoolDate,prettyDate } from '../lib/date'
import { supabase } from '../lib/supabase'
import type { DailySummary,SchoolClass } from '../types'

export function Dashboard(){const {profile}=useAuth();return profile?.role==='SECTION_HEAD'?<AdminDashboard/>:<TeacherDashboard/>}
function TeacherDashboard(){const {profile}=useAuth();const [classes,setClasses]=useState<SchoolClass[]>([]),[submitted,setSubmitted]=useState<string[]>([]);const today=schoolDate()
 useEffect(()=>{(async()=>{const {data}=await supabase.from('teacher_class_assignments').select('classes(id,display_name,grade_id)').eq('teacher_id',profile!.id).eq('is_active',true);const list=(data||[]).flatMap((x:any)=>x.classes?[x.classes]:[]);setClasses(list);if(list.length){const {data:s}=await supabase.from('attendance_sessions').select('class_id').eq('attendance_date',today).in('class_id',list.map((c:any)=>c.id));setSubmitted((s||[]).map(x=>x.class_id))}})()},[profile,today])
 return <><div className="page-title"><div><h1>Good day, {profile?.full_name.split(' ')[0]}</h1><p>{prettyDate(today)}</p></div></div><div className="teacher-hero"><Clock3/><div><small>TODAY'S ATTENDANCE</small><h2>{classes.length?`${submitted.length}/${classes.length} classes submitted`:'No class assigned'}</h2></div></div><div className="class-grid">{classes.map(c=><article className="class-card" key={c.id}><div><span className="class-badge">{c.display_name}</span><h3>{submitted.includes(c.id)?'Attendance submitted':'Ready to mark attendance'}</h3><p>{submitted.includes(c.id)?'The register is safely recorded.':'Mark all present, then update exceptions.'}</p></div>{submitted.includes(c.id)?<span className="submitted"><CheckCircle2/> Submitted</span>:<Link className="primary" to={`/attendance?class=${c.id}`}>Mark Today's Attendance</Link>}</article>)}</div></>}
function AdminDashboard(){const today=schoolDate();const [classes,setClasses]=useState<SchoolClass[]>([]),[summaries,setSummaries]=useState<DailySummary[]>([])
 async function load(){const [{data:c},{data:s}]=await Promise.all([supabase.from('classes').select('id,display_name,grade_id').eq('is_active',true).order('display_name'),supabase.from('daily_class_summary').select('*').eq('attendance_date',today)]);setClasses((c||[]) as SchoolClass[]);setSummaries((s||[]) as DailySummary[])}
 useEffect(()=>{load();const channel=supabase.channel('dashboard-live').on('postgres_changes',{event:'*',schema:'public',table:'attendance_sessions'},load).subscribe();return()=>{void supabase.removeChannel(channel)}},[today])
 const submitted=classes.filter(c=>summaries.some(s=>s.class_id===c.id)),pending=classes.filter(c=>!summaries.some(s=>s.class_id===c.id));const totals=summaries.reduce((a,s)=>({present:a.present+s.present,absent:a.absent+s.absent,late:a.late+s.late,total:a.total+s.total}),{present:0,absent:0,late:0,total:0});const pct=totals.total?((totals.present+totals.late)*100/totals.total).toFixed(1):'—'
 return <><div className="page-title"><div><h1>Today's Attendance</h1><p>{prettyDate(today)} · Live submission overview</p></div><button className="secondary" onClick={load}>Refresh</button></div><div className="stats"><Stat label="Present" value={totals.present} tone="green"/><Stat label="Absent" value={totals.absent} tone="red"/><Stat label="Late" value={totals.late} tone="amber"/><Stat label="Attendance" value={`${pct}%`} tone="blue"/><Stat label="Submitted" value={`${submitted.length}/${classes.length}`} tone="blue"/></div>{pending.length>0&&<section className="pending"><AlertCircle/><div><strong>Pending Classes</strong><p>{pending.map(c=>c.display_name).join(' · ')}</p></div></section>}<div className="grade-columns">{['10','11'].map(grade=><section className="panel" key={grade}><h2>Grade {grade}</h2>{classes.filter(c=>c.display_name.startsWith(grade+'-')).map(c=>{const s=summaries.find(x=>x.class_id===c.id);return <Link className="submission-row" to={s?`/history?session=${s.session_id}`:'#'} key={c.id}><span className="class-badge">{c.display_name}</span>{s?<><span className="submitted"><CheckCircle2/> Submitted</span><span>{s.present}/{s.total}</span><strong>{s.attendance_percentage}%</strong></>:<><span className="waiting"><Clock3/> Not submitted</span><span>—</span><strong>—</strong></>}</Link>})}</section>)}</div></>}
function Stat({label,value,tone}:{label:string,value:string|number,tone:string}){return <article className={`stat ${tone}`}><small>{label}</small><strong>{value}</strong><Users size={19}/></article>}

