import {useEffect,useState,type FormEvent} from 'react'
import {Link} from 'react-router-dom'
import {CalendarClock,MoreVertical,Search,UserRound} from 'lucide-react'
import {api} from '../lib/api'
import type {SchoolClass,Student} from '../types'
type S=Student&{display_name:string}
type T={id:string;full_name:string;username:string;is_active:number;classes:SchoolClass[];class_teacher_of?:SchoolClass|null}
type Period={period_no:number;subject:string;teacher_id:string}

export function Students(){const [students,setStudents]=useState<S[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[search,setSearch]=useState(''),[form,setForm]=useState({admission_number:'',full_name:'',class_id:''}),[error,setError]=useState('');async function load(){try{const [s,c]=await Promise.all([api<{students:S[]}>('/api/students'),api<{classes:SchoolClass[]}>('/api/classes')]);setStudents(s.students);setClasses(c.classes);setForm(x=>({...x,class_id:x.class_id||c.classes[0]?.id||''}))}catch{setError('Could not load students.')}}useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();setError('');try{await api('/api/students',{method:'POST',body:JSON.stringify(form)});setForm(x=>({...x,admission_number:'',full_name:''}));await load()}catch(e){setError(e instanceof Error&&e.message==='admission_number_exists'?'Admission number already exists.':'Could not add student.')}}
 return <><div className="screen-title-row"><div><h1>Classes & Students</h1><p>Manage students across Grades 6 and 7.</p></div></div><label className="search modern-search"><Search/><input placeholder="Search student name…" value={search} onChange={e=>setSearch(e.target.value)}/></label><form className="inline-form" onSubmit={add}><input required placeholder="Admission number" value={form.admission_number} onChange={e=>setForm({...form,admission_number:e.target.value})}/><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><button className="primary">Add Student</button></form>{error&&<div className="error">{error}</div>}<section className="data-list">{students.filter(s=>`${s.full_name} ${s.admission_number}`.toLowerCase().includes(search.toLowerCase())).map(s=><article key={s.id}><div><small>{s.admission_number} · {s.display_name}</small><strong>{s.full_name}</strong></div><select value={s.class_id} onChange={async e=>{await api(`/api/students/${s.id}`,{method:'PUT',body:JSON.stringify({class_id:e.target.value,reason:'Section Head transfer'})});load()}}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><span className={s.is_active?'status-pill active':'status-pill waiting'}>{s.is_active?'Active':'Inactive'}</span><button className="link" onClick={async()=>{if(confirm(`${s.is_active?'Deactivate':'Reactivate'} ${s.full_name}?`)){await api(`/api/students/${s.id}`,{method:'PUT',body:JSON.stringify({is_active:!s.is_active})});load()}}}>{s.is_active?'Deactivate':'Reactivate'}</button></article>)}</section></>}

export function Teachers(){const [rows,setRows]=useState<T[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[form,setForm]=useState({full_name:'',username:'',password:'',class_ids:[] as string[],class_teacher_id:''}),[error,setError]=useState('');async function load(){try{const [t,c]=await Promise.all([api<{teachers:T[]}>('/api/teachers'),api<{classes:SchoolClass[]}>('/api/classes')]);setRows(t.teachers);setClasses(c.classes)}catch{setError('Could not load teachers.')}}useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();setError('');try{await api('/api/teachers',{method:'POST',body:JSON.stringify(form)});setForm({full_name:'',username:'',password:'',class_ids:[],class_teacher_id:''});load()}catch(e){setError(e instanceof Error&&e.message==='username_exists'?'Username already exists.':'Could not create teacher. Password must be at least 10 characters.')}}
 return <><div className="screen-title-row"><div><h1>Teachers Management</h1><p>Accounts, class access and class-teacher assignments.</p></div><Link className="secondary icon-button" to="/timetable"><CalendarClock size={17}/> Timetable</Link></div><form className="teacher-form" onSubmit={add}><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required minLength={10} type="password" placeholder="Temporary password (10+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label>Class teacher of<select value={form.class_teacher_id} onChange={e=>setForm({...form,class_teacher_id:e.target.value})}><option value="">Not a class teacher</option>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></label><div className="check-grid">{classes.map(c=><label key={c.id}><input type="checkbox" checked={form.class_ids.includes(c.id)} onChange={e=>setForm({...form,class_ids:e.target.checked?[...form.class_ids,c.id]:form.class_ids.filter(x=>x!==c.id)})}/>{c.display_name}</label>)}</div><button className="primary">+ Add Teacher</button></form>{error&&<div className="error">{error}</div>}<section className="teacher-list">{rows.map(t=><article key={t.id}><span className="teacher-avatar"><UserRound/></span><div><strong>{t.full_name}</strong><small>{t.class_teacher_of?`Class Teacher · ${t.class_teacher_of.display_name}`:`@${t.username}`}</small></div><span className={t.is_active?'status-pill active':'status-pill waiting'}>{t.is_active?'Active':'Disabled'}</span><button className="more" title={t.is_active?'Disable teacher':'Enable teacher'} onClick={async()=>{await api(`/api/teachers/${t.id}`,{method:'PUT',body:JSON.stringify({is_active:!t.is_active})});load()}}><MoreVertical/></button></article>)}</section></>}

export function Timetable(){const [classes,setClasses]=useState<SchoolClass[]>([]),[teachers,setTeachers]=useState<T[]>([]),[classId,setClassId]=useState(''),[periods,setPeriods]=useState<Period[]>(Array.from({length:9},(_,i)=>({period_no:i+1,subject:'',teacher_id:''}))),[msg,setMsg]=useState('')
 useEffect(()=>{Promise.all([api<{classes:SchoolClass[]}>('/api/classes'),api<{teachers:T[]}>('/api/teachers')]).then(([c,t])=>{setClasses(c.classes);setTeachers(t.teachers);setClassId(c.classes[0]?.id||'')})},[])
 useEffect(()=>{if(!classId)return;api<{periods:any[]}>(`/api/timetable?class_id=${classId}`).then(x=>{const by=new Map(x.periods.map(p=>[Number(p.period_no),p]));setPeriods(Array.from({length:9},(_,i)=>{const p:any=by.get(i+1);return{period_no:i+1,subject:p?.subject||'',teacher_id:p?.teacher_id||''}}))}).catch(()=>setMsg('Deploy the latest Worker and database migration to configure timetables.'))},[classId])
 function patch(n:number,k:'subject'|'teacher_id',v:string){setPeriods(ps=>ps.map(p=>p.period_no===n?{...p,[k]:v}:p))}
 async function save(){const active=periods.filter(p=>p.subject.trim());try{await api('/api/timetable',{method:'PUT',body:JSON.stringify({class_id:classId,periods:active})});setMsg('Timetable saved ✓')}catch{setMsg('Could not save timetable. Deploy the latest backend first.')}}
 return <><div className="screen-title-row"><div><h1>Timetable / Period Setup</h1><p>Configure Periods 1–9, subjects and teachers.</p></div><select value={classId} onChange={e=>setClassId(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></div><section className="timetable-card"><div className="timetable-head"><span>Period</span><span>Subject</span><span>Teacher</span></div>{periods.map(p=><div className="timetable-row" key={p.period_no}><strong>{p.period_no}</strong><input placeholder="Subject" value={p.subject} onChange={e=>patch(p.period_no,'subject',e.target.value)}/><select value={p.teacher_id} onChange={e=>patch(p.period_no,'teacher_id',e.target.value)}><option value="">Select teacher</option>{teachers.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></div>)}</section>{msg&&<div className={msg.includes('✓')?'notice':'error'}>{msg}</div>}<button className="submit" onClick={save}>Save Timetable</button></>}

export function Placeholder({title,description}:{title:string;description:string}){return <><div className="screen-title-row"><div><h1>{title}</h1><p>{description}</p></div></div></>}