import { useEffect,useState,type FormEvent } from 'react'
import { supabase } from '../lib/supabase'
import type { SchoolClass,Student } from '../types'

export function Students(){const [students,setStudents]=useState<(Student&{classes:{display_name:string}})[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[search,setSearch]=useState(''),[form,setForm]=useState({admission_number:'',full_name:'',class_id:''}),[error,setError]=useState('')
 async function load(){const [{data:s},{data:c}]=await Promise.all([supabase.from('students').select('*,classes(display_name)').order('full_name'),supabase.from('classes').select('*').eq('is_active',true).order('display_name')]);setStudents((s||[]) as any);setClasses((c||[]) as SchoolClass[]);if(!form.class_id&&c?.length)setForm(x=>({...x,class_id:c[0].id}))}useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();setError('');const {error}=await supabase.from('students').insert(form);if(error)setError(error.message);else{setForm(x=>({...x,admission_number:'',full_name:''}));await load()}}
 return <><div className="page-title"><div><h1>Students</h1><p>Add, search, transfer or deactivate students without deleting history.</p></div><input placeholder="Search students" value={search} onChange={e=>setSearch(e.target.value)}/></div><form className="inline-form" onSubmit={add}><input required placeholder="Admission number" value={form.admission_number} onChange={e=>setForm({...form,admission_number:e.target.value})}/><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><button className="primary">Add student</button></form>{error&&<div className="error">{error}</div>}<section className="data-list">{students.filter(s=>`${s.full_name} ${s.admission_number}`.toLowerCase().includes(search.toLowerCase())).map(s=><article key={s.id}><div><small>{s.admission_number}</small><strong>{s.full_name}</strong></div><span className="class-badge">{s.classes?.display_name}</span><span>{s.is_active?'Active':'Inactive'}</span><button className="link" onClick={async()=>{if(confirm(`${s.is_active?'Deactivate':'Reactivate'} ${s.full_name}?`)){await supabase.from('students').update({is_active:!s.is_active}).eq('id',s.id);load()}}}>{s.is_active?'Deactivate':'Reactivate'}</button></article>)}</section></>}

export function Teachers(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('profiles').select('id,full_name,role,is_active,teacher_class_assignments(classes(display_name))').eq('role','TEACHER').then(({data})=>setRows(data||[]))},[]);return <><div className="page-title"><div><h1>Teachers</h1><p>Teacher accounts are created securely through Supabase Auth, then assigned here.</p></div></div><section className="data-list">{rows.map(t=><article key={t.id}><div><strong>{t.full_name}</strong><small>{t.id}</small></div><span>{t.teacher_class_assignments?.map((a:any)=>a.classes?.display_name).filter(Boolean).join(', ')||'No class assigned'}</span><span>{t.is_active?'Active':'Disabled'}</span></article>)}</section></>}

export function Placeholder({title,description}:{title:string;description:string}){return <><div className="page-title"><div><h1>{title}</h1><p>{description}</p></div></div><section className="panel empty"><h2>{title} workspace</h2><p>This secured area is connected to the shared database. Configure production data to begin.</p></section></>}

