import {useEffect,useState,type FormEvent} from 'react'
import {api} from '../lib/api'
import type {SchoolClass,Student} from '../types'
type S=Student&{display_name:string};type T={id:string;full_name:string;username:string;is_active:number;classes:SchoolClass[]}
export function Students(){const [students,setStudents]=useState<S[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[search,setSearch]=useState(''),[form,setForm]=useState({admission_number:'',full_name:'',class_id:''}),[error,setError]=useState('');async function load(){try{const [s,c]=await Promise.all([api<{students:S[]}>('/api/students'),api<{classes:SchoolClass[]}>('/api/classes')]);setStudents(s.students);setClasses(c.classes);setForm(x=>({...x,class_id:x.class_id||c.classes[0]?.id||''}))}catch{setError('Could not load students.')}}useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();setError('');try{await api('/api/students',{method:'POST',body:JSON.stringify(form)});setForm(x=>({...x,admission_number:'',full_name:''}));await load()}catch(e){setError(e instanceof Error&&e.message==='admission_number_exists'?'Admission number already exists.':'Could not add student.')}}
 return <><div className="page-title"><div><h1>Students</h1><p>Add, transfer, search or deactivate students without deleting history.</p></div><input placeholder="Search students" value={search} onChange={e=>setSearch(e.target.value)}/></div><form className="inline-form" onSubmit={add}><input required placeholder="Admission number" value={form.admission_number} onChange={e=>setForm({...form,admission_number:e.target.value})}/><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><button className="primary">Add student</button></form>{error&&<div className="error">{error}</div>}<section className="data-list">{students.filter(s=>`${s.full_name} ${s.admission_number}`.toLowerCase().includes(search.toLowerCase())).map(s=><article key={s.id}><div><small>{s.admission_number}</small><strong>{s.full_name}</strong></div><select value={s.class_id} onChange={async e=>{await api(`/api/students/${s.id}`,{method:'PUT',body:JSON.stringify({class_id:e.target.value,reason:'Section Head transfer'})});load()}}>{classes.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><span>{s.is_active?'Active':'Inactive'}</span><button className="link" onClick={async()=>{if(confirm(`${s.is_active?'Deactivate':'Reactivate'} ${s.full_name}?`)){await api(`/api/students/${s.id}`,{method:'PUT',body:JSON.stringify({is_active:!s.is_active})});load()}}}>{s.is_active?'Deactivate':'Reactivate'}</button></article>)}</section></>}
export function Teachers(){const [rows,setRows]=useState<T[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[form,setForm]=useState({full_name:'',username:'',password:'',class_ids:[] as string[]}),[error,setError]=useState('');async function load(){try{const [t,c]=await Promise.all([api<{teachers:T[]}>('/api/teachers'),api<{classes:SchoolClass[]}>('/api/classes')]);setRows(t.teachers);setClasses(c.classes)}catch{setError('Could not load teachers.')}}useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();setError('');try{await api('/api/teachers',{method:'POST',body:JSON.stringify(form)});setForm({full_name:'',username:'',password:'',class_ids:[]});load()}catch(e){setError(e instanceof Error&&e.message==='username_exists'?'Username already exists.':'Could not create teacher. Password must be at least 10 characters.')}}
 return <><div className="page-title"><div><h1>Teachers</h1><p>Create secure teacher accounts and assign classes.</p></div></div><form className="teacher-form" onSubmit={add}><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required minLength={10} type="password" placeholder="Temporary password (10+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><div className="check-grid">{classes.map(c=><label key={c.id}><input type="checkbox" checked={form.class_ids.includes(c.id)} onChange={e=>setForm({...form,class_ids:e.target.checked?[...form.class_ids,c.id]:form.class_ids.filter(x=>x!==c.id)})}/>{c.display_name}</label>)}</div><button className="primary">Create teacher</button></form>{error&&<div className="error">{error}</div>}<section className="data-list">{rows.map(t=><article key={t.id}><div><strong>{t.full_name}</strong><small>@{t.username}</small></div><span>{t.classes?.map(c=>c.display_name).join(', ')||'No class assigned'}</span><span>{t.is_active?'Active':'Disabled'}</span><button className="link" onClick={async()=>{await api(`/api/teachers/${t.id}`,{method:'PUT',body:JSON.stringify({is_active:!t.is_active})});load()}}>{t.is_active?'Disable':'Enable'}</button></article>)}</section></>}
export function Placeholder({title,description}:{title:string;description:string}){return <><div className="page-title"><div><h1>{title}</h1><p>{description}</p></div></div></>}
