import {useEffect,useState} from 'react'
import {api} from '../lib/api'
import {schoolDate,prettyDate} from '../lib/date'
type P={id:string;period_no:number;subject:string;teacher_name:string|null;status?:string|null}
const choices=[['ARRIVED','ARRIVED'],['NOT_ARRIVED','NOT ARRIVED'],['DELAYED','DELAYED'],['RELIEF','RELIEF'],['NOT_ARRIVED_RELIEF','NOT RELIEF']] as const
export function PeriodAttendance(){const date=schoolDate();const [periods,setPeriods]=useState<P[]>([]),[className,setClassName]=useState(''),[statuses,setStatuses]=useState<Record<string,string>>({}),[msg,setMsg]=useState('')
 async function load(){try{const x:any=await api('/api/period-attendance/today?date='+date);setPeriods(x.periods);setClassName(x.class_name);setStatuses(Object.fromEntries(x.periods.filter((p:P)=>p.status).map((p:P)=>[p.id,p.status])))}catch(e:any){setMsg(e.message==='class_teacher_not_assigned'?'You are not assigned as a class teacher.':'Could not load teacher attendance.')}} useEffect(()=>{load()},[])
 async function save(){if(periods.some(p=>!statuses[p.id])){setMsg('Mark every period before saving.');return}try{await api('/api/period-attendance',{method:'POST',body:JSON.stringify({date,records:periods.map(p=>({period_id:p.id,status:statuses[p.id]}))})});setMsg('Teacher attendance saved ✓')}catch{setMsg('Could not save teacher attendance.')}}
 return <><div className="page-title"><div><h1>Teachers Attendance & Status</h1><p>{className?className+' · ':''}{prettyDate(date)}</p></div></div>{msg&&<div className={msg.includes('✓')?'notice':'error'}>{msg}</div>}<div className="teacher-attendance-table"><table><thead><tr><th>Period</th>{choices.map(([v,l])=><th key={v}>{l}</th>)}</tr></thead><tbody>{periods.map(p=><tr key={p.id}><th><span>{p.period_no}</span><small>{p.subject}{p.teacher_name?' · '+p.teacher_name:''}</small></th>{choices.map(([v])=><td key={v}><label className="status-check"><input type="radio" name={'period-'+p.id} checked={statuses[p.id]===v} onChange={()=>setStatuses(s=>({...s,[p.id]:v}))}/><span/></label></td>)}</tr>)}</tbody></table></div>{periods.length>0&&<button className="submit" onClick={save}>Save Teacher Attendance</button>}</>}
