import {useEffect,useState} from 'react'
import {Camera,LogOut,UserRound} from 'lucide-react'
import {api} from '../lib/api'
import {useAuth} from '../AuthContext'

function compressPhoto(file:File){return new Promise<string>((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const max=512,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('canvas_unavailable');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',0.82))}catch(e){reject(e)}finally{URL.revokeObjectURL(url)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('invalid_image'))};img.src=url})}

export function Profile(){
 const auth=useAuth(),profile=auth.profile
 const [name,setName]=useState(profile?.full_name||''),[photo,setPhoto]=useState(()=>localStorage.getItem('school_attendance_profile_photo')||''),[msg,setMsg]=useState(''),[photoBusy,setPhotoBusy]=useState(false)
 useEffect(()=>setName(profile?.full_name||''),[profile?.full_name])
 async function choose(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/')){setMsg('Please choose an image file.');return}setPhotoBusy(true);setMsg('');try{const v=await compressPhoto(file);localStorage.setItem('school_attendance_profile_photo',v);setPhoto(v);window.dispatchEvent(new Event('profile-photo-changed'));setMsg('Profile picture updated ✓')}catch{setMsg('Could not process that image. Please choose another photo.')}finally{setPhotoBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setMsg('');try{const d=await api<{user:any}>('/api/profile',{method:'PUT',body:JSON.stringify({full_name:name})});auth.setProfile(d.user);setMsg('Profile updated ✓')}catch(err){setMsg(err instanceof Error?err.message:'Could not update profile.')}}
 return <><section className="profile-hero"><div className="profile-photo">{photo?<img src={photo} alt="Profile"/>:<UserRound/>}</div><h2>{profile?.full_name}</h2><p>{profile?.role==='SECTION_HEAD'?'Section Head':'Class Teacher'}</p><small>@{profile?.username}</small></section><section className="profile-card"><label className="secondary profile-photo-button"><Camera size={17}/>{photoBusy?'Processing photo…':'Change Profile Picture'}<input type="file" accept="image/*" onChange={choose} disabled={photoBusy} hidden/></label><small className="profile-photo-note">Choose a photo from your phone. It will be resized automatically for the profile.</small><form onSubmit={save} className="profile-form"><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Username<input value={profile?.username||''} readOnly disabled/><small>Username cannot be changed.</small></label><button className="primary" type="submit">Save Changes</button></form>{msg&&<div className={msg.includes('✓')?'notice':'error'}>{msg}</div>}</section><button className="profile-logout" type="button" onClick={()=>auth.signOut()}><LogOut size={18}/> Logout</button></>
}